# Dependencies
markdown:         rdiscount
highlighter:      rouge
 
# Permalinks
permalink:        pretty
 
# Server
destination:      _gh_pages
host:             127.0.0.1
port:             9001
baseurl:          /
encoding:         UTF-8